<x-layouts.public title="Tentang Kami" :description="$settings['church_description']??null" :image="asset('images/about/menara-hananeel-hero.webp')">
    <section class="relative isolate flex min-h-[42rem] items-end overflow-hidden bg-primary pt-40 text-white lg:min-h-[46rem] lg:pt-48" x-data="parallaxBackground">
        <div class="absolute -inset-y-16 inset-x-0 -z-20 scale-110 bg-cover bg-[68%_center] will-change-transform sm:bg-center" style="background-image: url('{{ asset('images/about/menara-hananeel-hero.webp') }}')" :style="`transform: translate3d(0, ${offset}px, 0); background-image: url('{{ asset('images/about/menara-hananeel-hero.webp') }}')`" aria-hidden="true"></div>
        <div class="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(30,12,15,.88)_0%,rgba(30,12,15,.67)_43%,rgba(30,12,15,.20)_76%,rgba(30,12,15,.10)_100%)]" aria-hidden="true"></div>
        <div class="absolute inset-0 -z-10 bg-[linear-gradient(0deg,rgba(20,10,10,.64)_0%,transparent_58%)]" aria-hidden="true"></div>
        <div class="page-container pb-20 lg:pb-24">
            <p class="text-sm font-bold uppercase tracking-[.04em] text-white/75"><span class="text-signal-light">•</span> Tentang Kami</p>
            <h1 class="mt-6 max-w-4xl text-5xl leading-none text-white drop-shadow-sm md:text-7xl">Menara penjaga kota yang berdiri dalam doa dan kasih.</h1>
            <p class="mt-8 max-w-2xl text-lg leading-8 text-white/80 md:text-xl">{{ $settings['church_description']?:'JKI Hananeel Cinta dipanggil untuk berjaga, membangun, dan membawa kasih Tuhan bagi keluarga, kota, serta bangsa-bangsa.' }}</p>
        </div>
    </section>
    <section class="bg-lifted py-20 lg:py-28"><div class="page-container grid gap-6 lg:grid-cols-2"><x-card title="Visi"><p class="whitespace-pre-line text-lg leading-8 text-slate">{{ $settings['church_vision']?:'Menjadi menara penjaga kota yang teguh dalam doa, peka melihat kebutuhan zaman, dan menghadirkan kasih Tuhan.' }}</p></x-card><x-card title="Misi"><p class="whitespace-pre-line text-lg leading-8 text-slate">{{ $settings['church_mission']?:'Membangun jemaat yang berjaga dalam doa, berakar dalam Firman, melayani dengan kasih, dan membawa pemulihan bagi kota serta bangsa-bangsa.' }}</p></x-card></div></section>
    <section class="py-20 lg:py-28"><div class="page-container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><p class="text-sm font-bold uppercase tracking-[.04em] text-slate"><span class="text-signal-light">•</span> Identitas</p><div><h2 class="text-4xl">Hananeel, menara penjaga kota</h2><div class="mt-7 whitespace-pre-line text-lg leading-8 text-slate">{{ $settings['church_history']?:'Hananeel menggambarkan sebuah menara yang berdiri sebagai tanda pemulihan dan pengharapan bagi kota. Identitas ini mengingatkan kami untuk setia berjaga dalam doa, membangun kehidupan, serta menghadirkan kasih Tuhan bagi setiap generasi.' }}</div></div></div></section>
    <section class="bg-primary py-20 text-canvas"><div class="page-container"><div class="mb-10 grid gap-6 lg:grid-cols-2"><h2 class="text-4xl lg:text-5xl">Jadwal ibadah dan persekutuan.</h2><p class="text-lg leading-8 text-canvas/70">Mari datang, bertumbuh, dan mengalami Tuhan bersama keluarga JKI Hananeel Cinta.</p></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article class="service-card"><p class="service-day">Minggu · 07:00 & 10:00 WIB</p><h3>Ibadah Raya</h3></article><article class="service-card"><p class="service-day">Minggu · 07:00 & 10:00 WIB</p><h3>Sekolah Minggu</h3></article><article class="service-card"><p class="service-day">Selasa · 19:00 WIB</p><h3>Holy Spirit Night</h3></article><article class="service-card"><p class="service-day">Sabtu · 17:00 WIB</p><h3>Rock Jakarta</h3><p>Youth Service</p></article></div><a href="{{ route('family-altars.index') }}" class="mt-8 inline-flex items-center gap-2 text-white underline decoration-white/30 underline-offset-4 hover:decoration-white">Lihat jadwal Mezbah Keluarga <x-icon name="arrow-right"/></a></div></section>
</x-layouts.public>
