<x-layouts.public :description="$settings['seo_description']??null">
    <section class="page-container flex min-h-screen items-center pb-16 pt-36 lg:pt-40">
        <div class="grid w-full items-end gap-10 lg:grid-cols-[1.3fr_.7fr]">
            <div><p class="eyebrow">{{ $settings['church_name']??'JKI Hananeel Cinta' }}</p><h1 class="mt-6 max-w-4xl text-5xl leading-[.98] md:text-6xl lg:text-[5rem]">{{ $settings['church_tagline']?:'Rumah untuk bertumbuh dalam iman, pengharapan, dan kasih.' }}</h1></div>
            <div class="pb-2"><p class="text-lg leading-7 text-slate">{{ $settings['church_description']?:'Setiap pribadi berharga, dipanggil, dan memiliki tempat dalam keluarga Allah.' }}</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('about') }}" class="button-primary">Tentang Kami <x-icon name="arrow-right"/></a><a href="{{ route('prayer-request.create') }}" class="button-secondary">Prayer Request</a></div></div>
            <div class="orbital-stage col-span-full min-h-96 p-7 md:min-h-[31rem] md:p-12">
                <p class="pointer-events-none absolute -bottom-5 -left-3 -z-10 text-[5rem] font-medium leading-none tracking-[-.04em] text-white/[.035] sm:text-[8rem] lg:text-[11rem]">Hananeel</p>
                <div class="relative z-10 flex h-full min-h-[20rem] flex-col justify-between gap-12 md:min-h-[25rem] md:flex-row md:items-end"><div class="max-w-2xl self-end"><p class="text-xs font-bold uppercase tracking-[.08em] text-canvas/55">Kasih yang mengubahkan</p><h2 class="mt-4 text-4xl leading-tight md:text-5xl">Berakar dalam Firman.<br>Bertumbuh dalam komunitas.</h2></div><div class="relative mr-4 mt-4 self-end md:mb-5 md:mr-10 md:self-start"><div class="grid h-36 w-36 place-items-center rounded-full border border-white/20 bg-white/5 p-5 text-center text-sm leading-5 text-white/75 backdrop-blur sm:h-44 sm:w-44"><span><strong class="block text-3xl font-medium text-white">Satu</strong> keluarga dalam kasih Kristus</span></div><a href="{{ route('contact') }}" class="satellite-link absolute -bottom-2 -right-2" aria-label="Kunjungi JKI Hananeel Cinta"><x-icon name="arrow-right"/></a></div></div>
            </div>
        </div>
    </section>
    <section class="bg-lifted py-20 lg:py-28"><div class="page-container"><div class="mb-12 flex items-end justify-between gap-6"><div><p class="eyebrow">Terbaru</p><h2 class="mt-3 text-4xl lg:text-5xl">Pengumuman gereja</h2></div><a href="{{ route('announcements.index') }}" class="text-link hidden sm:inline-flex">Lihat semua <x-icon name="arrow-right"/></a></div><div class="grid gap-12 md:grid-cols-3">@forelse($announcements as $announcement)@include('web.partials.announcement-card')@empty<x-empty-state class="md:col-span-3" title="Belum ada pengumuman" />@endforelse</div><a href="{{ route('announcements.index') }}" class="text-link mt-8 sm:hidden">Lihat semua <x-icon name="arrow-right"/></a></div></section>
    <section class="relative overflow-hidden py-20 lg:py-28"><p class="pointer-events-none absolute -right-10 top-6 text-[7rem] font-medium leading-none tracking-[-.04em] text-bone/70 md:text-[11rem]">Firman</p><div class="page-container relative"><div class="mb-12"><p class="eyebrow">Renungan</p><h2 class="mt-3 text-4xl lg:text-5xl">Pastor Message terbaru</h2></div><div class="grid gap-6 md:grid-cols-3">@forelse($pastorMessages as $message)@include('web.partials.pastor-card')@empty<x-empty-state class="md:col-span-3" title="Belum ada Pastor Message" />@endforelse</div></div></section>
    <section class="bg-lifted py-20 lg:py-28"><div class="page-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div class="lg:sticky lg:top-32 lg:self-start"><p class="eyebrow">Komunitas</p><h2 class="mt-3 text-4xl lg:text-5xl">Bertumbuh melalui Mezbah Keluarga.</h2><p class="mt-5 max-w-md text-lg leading-7 text-slate">Temukan keluarga rohani terdekat untuk saling menguatkan, belajar Firman, dan bertumbuh bersama.</p><a href="{{ route('family-altars.index') }}" class="button-primary mt-7">Temukan lokasi <x-icon name="arrow-right"/></a></div><div class="grid gap-4 sm:grid-cols-2">@forelse($familyAltars as $altar)<article class="group rounded-[40px] border border-ink/6 bg-white p-6 transition duration-200 hover:-translate-y-1 hover:shadow-[0_24px_48px_rgba(0,0,0,.06)]"><div class="flex items-start justify-between gap-3"><x-badge>{{ $altar->day_of_week->label() }}</x-badge><span class="grid h-10 w-10 place-items-center rounded-full bg-canvas text-slate transition group-hover:bg-primary group-hover:text-white"><x-icon name="map" :size="18"/></span></div><h3 class="mt-5 text-2xl">{{ $altar->name }}</h3><p class="mt-2 text-slate">{{ $altar->start_time }} · {{ $altar->pic_name }}</p></article>@empty<x-empty-state class="sm:col-span-2" title="Jadwal segera hadir" />@endforelse</div></div></section>
</x-layouts.public>
