[program:hananeel-cinta-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/hananeel-cinta/current/artisan queue:work database --sleep=3 --tries=3 --timeout=90 --max-time=3600
directory=/var/www/hananeel-cinta/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/hananeel-cinta-worker.log
stopwaitsecs=3600
