@php
    $defaultFields = [['key'=>'name','label'=>'Nama lengkap','type'=>'text','required'=>true,'options'=>[]]];
    $initialFields = old('registration_fields', $event->registration_fields ?: $defaultFields);
@endphp
<x-layouts.admin :title="$title">
    <header class="event-toolbar"><div><a href="{{ $event->exists ? route('admin.events.show',$event) : route('admin.events.index') }}" class="text-link !min-h-8"><x-icon name="arrow-left" :size="17"/>Kembali</a><p class="event-kicker mt-5">Event builder</p><h1 class="event-title">{{ $title }}</h1><p class="event-subtitle">Lengkapi informasi acara, lalu susun data yang perlu diisi setiap peserta.</p></div></header>
    @if($errors->any())<x-alert type="error" class="mb-6">{{ $errors->first() }}</x-alert>@endif
    <form method="post" action="{{ $event->exists ? route('admin.events.update',$event) : route('admin.events.store') }}" enctype="multipart/form-data" class="space-y-6" x-data="eventFieldBuilder(@js($initialFields))">
        @csrf @if($event->exists)@method('PUT')@endif
        <section class="event-panel"><div class="event-panel-header"><div><h2 class="text-xl">Informasi event</h2><p class="mt-1 text-sm text-slate">Informasi utama yang dilihat jemaat</p></div></div><div class="event-panel-body grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><x-input name="title" label="Nama event" :value="old('title',$event->title)" required/></div><div class="md:col-span-2"><x-textarea name="description" label="Deskripsi event" required>{{ old('description',$event->description) }}</x-textarea></div><x-input name="starts_at" label="Tanggal mulai" type="datetime-local" :value="old('starts_at',$event->starts_at?->format('Y-m-d\TH:i'))" required/><x-input name="ends_at" label="Tanggal selesai (opsional)" type="datetime-local" :value="old('ends_at',$event->ends_at?->format('Y-m-d\TH:i'))"/><div class="md:col-span-2"><x-input name="image" label="Gambar informasi event" type="file" accept="image/jpeg,image/png,image/webp"/>@if($event->imageUrl())<img src="{{ $event->imageUrl() }}" alt="Gambar event saat ini" class="mt-4 h-40 rounded-2xl object-cover">@endif</div><label class="flex min-h-16 items-center gap-4 rounded-2xl border border-ink/10 bg-canvas/60 p-4 md:col-span-2"><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" class="h-5 w-5" @checked(old('is_published',$event->is_published))><span><strong class="block">Buka pendaftaran</strong><span class="mt-1 block text-sm text-slate">Link publik dapat diakses dan jemaat bisa mengirim formulir.</span></span></label></div></section>
        <section class="event-panel"><div class="event-panel-header"><div><h2 class="text-xl">Formulir pendaftaran</h2><p class="mt-1 max-w-2xl text-sm text-slate">Nama lengkap selalu wajib untuk tiket. Tambahkan hanya data yang benar-benar dibutuhkan.</p></div><button type="button" class="button-secondary mobile-full" @click="addField()"><x-icon name="plus"/>Tambah field</button></div><div class="event-panel-body space-y-4">
                <template x-for="(field,index) in fields" :key="field.uid"><div class="event-field-row"><div class="mb-4 flex items-center justify-between"><span class="text-xs font-semibold uppercase tracking-[.08em] text-slate" x-text="`Field ${index+1}`"></span><button type="button" class="grid h-10 w-10 place-items-center rounded-full text-signal hover:bg-red-50 disabled:hidden" @click="removeField(index)" :disabled="field.key === 'name'" aria-label="Hapus field"><x-icon name="close"/></button></div><div class="grid gap-4 md:grid-cols-[1fr_15rem]"><div><label class="mb-2 block text-sm font-semibold">Label untuk jemaat</label><input class="form-control" :name="`registration_fields[${index}][label]`" x-model="field.label" required @input="field.key === '' || field.autoKey ? setKey(field) : null"></div><div><label class="mb-2 block text-sm font-semibold">Tipe jawaban</label><select class="form-control" :name="`registration_fields[${index}][type]`" x-model="field.type"><option value="text">Teks singkat</option><option value="email">Email</option><option value="tel">Nomor telepon</option><option value="date">Tanggal</option><option value="select">Pilihan</option><option value="textarea">Teks panjang</option></select></div></div><input type="hidden" :name="`registration_fields[${index}][key]`" x-model="field.key"><div x-show="field.type === 'select'" x-cloak class="mt-4"><label class="mb-2 block text-sm font-semibold">Daftar pilihan</label><input class="form-control" x-model="field.optionsText" placeholder="Contoh: Laki-laki, Perempuan"><p class="mt-2 text-xs text-slate">Pisahkan setiap pilihan dengan koma.</p><template x-for="(option,optionIndex) in parsedOptions(field)" :key="`${field.uid}-${optionIndex}`"><input type="hidden" :name="`registration_fields[${index}][options][${optionIndex}]`" :value="option"></template></div><div class="mt-4 flex items-center gap-3 border-t border-ink/8 pt-4"><input type="hidden" :name="`registration_fields[${index}][required]`" value="0"><input type="checkbox" :name="`registration_fields[${index}][required]`" value="1" class="h-5 w-5" x-model="field.required" :disabled="field.key === 'name'"><span class="text-sm font-medium">Wajib diisi</span><span class="ml-auto font-mono text-xs text-slate" x-text="field.key"></span></div></div></template>
        </div></section>
        <div class="mobile-action-bar sticky flex justify-end rounded-2xl border border-white/70 bg-white/85 p-3 shadow-lg backdrop-blur-xl"><x-button type="submit" class="mobile-full">{{ $event->exists ? 'Simpan perubahan' : 'Buat event' }}</x-button></div>
    </form>
</x-layouts.admin>
