@php
    $defaultFields = [['key'=>'name','label'=>'Nama lengkap','type'=>'text','required'=>true,'options'=>[]]];
    $initialFields = old('registration_fields', $event->registration_fields ?: $defaultFields);
@endphp
<x-layouts.admin :title="$title">
    <div class="mb-8"><a href="{{ $event->exists ? route('admin.events.show',$event) : route('admin.events.index') }}" class="text-link">← Kembali</a><h1 class="mt-4 text-4xl">{{ $title }}</h1><p class="mt-2 text-slate">Atur informasi event dan data apa saja yang perlu diisi jemaat.</p></div>
    @if($errors->any())<x-alert type="error" class="mb-6">{{ $errors->first() }}</x-alert>@endif
    <form method="post" action="{{ $event->exists ? route('admin.events.update',$event) : route('admin.events.store') }}" enctype="multipart/form-data" class="space-y-6" x-data="eventFieldBuilder(@js($initialFields))">
        @csrf @if($event->exists)@method('PUT')@endif
        <x-card title="Informasi Event"><div class="grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><x-input name="title" label="Nama event" :value="old('title',$event->title)" required/></div><div class="md:col-span-2"><x-textarea name="description" label="Deskripsi event" required>{{ old('description',$event->description) }}</x-textarea></div><x-input name="starts_at" label="Tanggal mulai" type="datetime-local" :value="old('starts_at',$event->starts_at?->format('Y-m-d\TH:i'))" required/><x-input name="ends_at" label="Tanggal selesai (opsional)" type="datetime-local" :value="old('ends_at',$event->ends_at?->format('Y-m-d\TH:i'))"/><div class="md:col-span-2"><x-input name="image" label="Gambar informasi event" type="file" accept="image/jpeg,image/png,image/webp"/>@if($event->imageUrl())<img src="{{ $event->imageUrl() }}" alt="" class="mt-4 h-36 rounded-xl object-cover">@endif</div><label class="flex min-h-12 items-center gap-3 md:col-span-2"><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" class="h-5 w-5" @checked(old('is_published',$event->is_published))><span><strong class="block">Publikasikan pendaftaran</strong><span class="text-sm text-slate">Jemaat dapat mengakses link dan mengisi formulir.</span></span></label></div></x-card>
        <x-card title="Field Pendaftaran">
            <div class="mb-6 flex flex-wrap items-start justify-between gap-4"><p class="max-w-2xl text-sm leading-6 text-slate">Nama lengkap wajib ada karena dipakai pada tiket. Tambahkan tanggal lahir, jenis kelamin, email, atau data lain sesuai kebutuhan event.</p><button type="button" class="button-secondary" @click="addField()"><x-icon name="plus"/>Tambah field</button></div>
            <div class="space-y-4">
                <template x-for="(field,index) in fields" :key="field.uid"><div class="rounded-2xl border border-ink/10 bg-canvas/50 p-5"><div class="grid gap-4 md:grid-cols-[1fr_13rem_auto]"><div><label class="mb-2 block text-sm font-semibold">Label</label><input class="form-control" :name="`registration_fields[${index}][label]`" x-model="field.label" required @input="field.key === '' || field.autoKey ? setKey(field) : null"></div><div><label class="mb-2 block text-sm font-semibold">Tipe data</label><select class="form-control" :name="`registration_fields[${index}][type]`" x-model="field.type"><option value="text">Teks singkat</option><option value="email">Email</option><option value="tel">Nomor telepon</option><option value="date">Tanggal</option><option value="select">Pilihan</option><option value="textarea">Teks panjang</option></select></div><button type="button" class="mt-7 grid h-12 w-12 place-items-center rounded-xl text-signal hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-30" @click="removeField(index)" :disabled="field.key === 'name'" aria-label="Hapus field"><x-icon name="close"/></button></div><input type="hidden" :name="`registration_fields[${index}][key]`" x-model="field.key"><div class="mt-4 flex items-center gap-3"><input type="hidden" :name="`registration_fields[${index}][required]`" value="0"><input type="checkbox" :name="`registration_fields[${index}][required]`" value="1" class="h-5 w-5" x-model="field.required" :disabled="field.key === 'name'"><span class="text-sm">Wajib diisi</span><span class="ml-auto font-mono text-xs text-slate" x-text="field.key"></span></div><div x-show="field.type === 'select'" x-cloak class="mt-4"><label class="mb-2 block text-sm font-semibold">Pilihan <span class="font-normal text-slate">(pisahkan dengan koma)</span></label><input class="form-control" x-model="field.optionsText" placeholder="Laki-laki, Perempuan"><template x-for="(option,optionIndex) in parsedOptions(field)" :key="`${field.uid}-${optionIndex}`"><input type="hidden" :name="`registration_fields[${index}][options][${optionIndex}]`" :value="option"></template></div></div></template>
            </div>
        </x-card>
        <div class="flex justify-end"><x-button type="submit">{{ $event->exists ? 'Simpan perubahan' : 'Buat event' }}</x-button></div>
    </form>
</x-layouts.admin>
